### ISSUE TITLE
Is HTTPS required to test on a read device?

### ISSUE THREAD

**Issue by jimvvv** [adamjberg/ios-push-notifications#1]
Hi,

Thanks for your sample code around how to use web push in ios16.4.
I'm trying to test it on my iPad (iPadOS 16.4). There is no response after clicking Subscribe button. Even if share the web app to Home Screen, it doesn't work.
But I noticed `Testing this on a real device requires an https connection.` I am wondering if it's required.

Thanks,
Jimmy

**Comment by EdmondChuiHW** [comment]
Yes HTTPS is required. This was mentioned in the article under [HTTPS Connection](https://devtails.xyz/@adam/how-to-setup-web-push-notifications-in-ios-safari#https-connection)

You can try something like https://ngrok.com to get an HTTPS address for testing
